# Site settings
title: Hugo Giraudel, front-end developer in Berlin
email: hugo.giraudel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Hugo Giraudel, I am a French front-end developer based in Berlin, focused on CSS and Sass.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hugogiraudel.com" # the base hostname & protocol for your site
twitter_username: HugoGiraudel
github_username:  HugoGiraudel

# Build settings
markdown: kramdown
paginate_path: /blog/page:num
paginate: 10
permalink: pretty
sass:
  style: :compressed
gems: [jekyll-paginate]
